/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.AdvertisementManagerRole;

import Business.Enterprise.AdvertisementEnterprise;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.time.LocalDateTime;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.util.Date;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author aakashbelide
 */
public class AddAdvertisementJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    AdvertisementEnterprise enterprise;
    
    private final JFileChooser fileChooser = new JFileChooser();
    ImageIcon advImage;

    /**
     * Creates new form AddAdvertisementJPanel
     */
    public AddAdvertisementJPanel(JPanel userProcessContainer, AdvertisementEnterprise enterprise) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        
        FileFilter jpegFilter = new FileNameExtensionFilter("JPEG file", "jpg", "jpeg");
        FileFilter pngFilter = new FileNameExtensionFilter("PNG file", "png", "png");
        
        fileChooser.addChoosableFileFilter(jpegFilter);
        fileChooser.addChoosableFileFilter(pngFilter);
        fileChooser.setFileFilter(pngFilter);
        
        setupSpinner();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbltitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblAdvName = new javax.swing.JLabel();
        txtAdvName = new javax.swing.JTextField();
        lblExpDatetime = new javax.swing.JLabel();
        spinExpDatetime = new javax.swing.JSpinner();
        lblLatitude = new javax.swing.JLabel();
        txtLatitude = new javax.swing.JTextField();
        lblLongitude = new javax.swing.JLabel();
        txtLongitude = new javax.swing.JTextField();
        btnAddAdv = new javax.swing.JButton();
        imageAdvertisement = new javax.swing.JLabel();
        btnAttach = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 102));

        lbltitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbltitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitle.setText("Add Advertisement");

        btnBack.setBackground(new java.awt.Color(0, 153, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/arrow.png"))); // NOI18N
        btnBack.setBorder(null);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(btnBack)
                .addGap(219, 219, 219)
                .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                .addGap(508, 508, 508))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        lblAdvName.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblAdvName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAdvName.setText("Advertisement Name:");

        lblExpDatetime.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblExpDatetime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblExpDatetime.setText("Expiry Date time:");

        lblLatitude.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblLatitude.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLatitude.setText("Latitude:");

        lblLongitude.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblLongitude.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLongitude.setText("Longitude:");

        btnAddAdv.setBackground(new java.awt.Color(0, 153, 255));
        btnAddAdv.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnAddAdv.setForeground(new java.awt.Color(255, 255, 255));
        btnAddAdv.setText("Add Advertisement");
        btnAddAdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAdvActionPerformed(evt);
            }
        });

        imageAdvertisement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageAdvertisement.setText("<Add Image>");
        imageAdvertisement.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        btnAttach.setBackground(new java.awt.Color(0, 153, 255));
        btnAttach.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnAttach.setForeground(new java.awt.Color(255, 255, 255));
        btnAttach.setText("Attach");
        btnAttach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttachActionPerformed(evt);
            }
        });

        btnRemove.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1061, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAdvName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblExpDatetime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblLatitude, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblLongitude, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLongitude)
                                    .addComponent(txtAdvName)
                                    .addComponent(txtLatitude)
                                    .addComponent(spinExpDatetime)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAddAdv, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)))
                        .addGap(210, 210, 210)
                        .addComponent(imageAdvertisement, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAttach, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)))
                .addGap(154, 154, 154))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAttach, btnRemove});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageAdvertisement, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAdvName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAdvName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinExpDatetime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblExpDatetime))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLatitude))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLongitude))
                        .addGap(27, 27, 27)
                        .addComponent(btnAddAdv)))
                .addGap(18, 18, 18)
                .addComponent(btnAttach)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRemove)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {spinExpDatetime, txtAdvName, txtLatitude, txtLongitude});

    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.userProcessContainer.remove(this);
        Component[] componentArray = this.userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        AdvertisementManagerWorkAreaJPanel advertisementManagerWorkAreaJPanel = (AdvertisementManagerWorkAreaJPanel) component;
        advertisementManagerWorkAreaJPanel.populateAdvTable();
        CardLayout layout = (CardLayout) this.userProcessContainer.getLayout();
        layout.previous(this.userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddAdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAdvActionPerformed
        // TODO add your handling code here:
        String advName = txtAdvName.getText();
        
        if (txtAdvName.getText().isBlank() || txtLatitude.getText().isBlank() || txtLongitude.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "All fields all mandatory.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (advImage == null) {
            JOptionPane.showMessageDialog(this, "Please attach an image for advertisement.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        LocalDateTime advExpDatetime;
        float advLat;
        float advLongi;
        
        try {
            advExpDatetime = getSelectedDateTime();
            
            if (advExpDatetime.isBefore(LocalDateTime.now())) {
                JOptionPane.showMessageDialog(this, "Expiry date must be in the future.", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid date.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            advLat = Float.parseFloat(txtLatitude.getText());
            advLongi = Float.parseFloat(txtLongitude.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please enter a latitude and longitude.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        this.enterprise.getAdvertisementCatalog().addAdvertisement(advName, advExpDatetime, advImage, advLat, advLongi);
        
        JOptionPane.showMessageDialog(this, "Advertisement created successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
        txtAdvName.setText("");
        resetSpinner();
        txtLatitude.setText("");
        txtLongitude.setText("");
        advImage = null;
        imageAdvertisement.setIcon(advImage);
    }//GEN-LAST:event_btnAddAdvActionPerformed

    private void btnAttachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttachActionPerformed
        // TODO add your handling code here:
        int returnVal = fileChooser.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            URL url;

            try {
                url = file.toURI().toURL();
                advImage = new ImageIcon(url);
                advImage = new ImageIcon(advImage.getImage().getScaledInstance(150, 350, Image.SCALE_SMOOTH));

                imageAdvertisement.setIcon(advImage);
            } catch (MalformedURLException ex) {
                JOptionPane.showMessageDialog(this, "There was an error in loading your image. Please try again.", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
    }//GEN-LAST:event_btnAttachActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        advImage = null;
        imageAdvertisement.setIcon(advImage);
    }//GEN-LAST:event_btnRemoveActionPerformed

    public void setupSpinner() {
        // Get the current LocalDateTime
        LocalDateTime now = LocalDateTime.now();

        // Convert LocalDateTime to Date
        Date nowDate = java.sql.Timestamp.valueOf(now);

        // Configure the SpinnerDateModel with the current date as the lower bound
        SpinnerDateModel dateModel = new SpinnerDateModel();
        dateModel.setStart(nowDate); // Set minimum date to current date
        spinExpDatetime.setModel(dateModel);

        // Add a custom editor to show both date and time in the spinner
        JSpinner.DateEditor dateEditor = new JSpinner.DateEditor(spinExpDatetime, "yyyy-MM-dd HH:mm");
        spinExpDatetime.setEditor(dateEditor);
    }
    
    // Method to retrieve the selected date as LocalDateTime
    public LocalDateTime getSelectedDateTime() {
        Date selectedDate = (Date) spinExpDatetime.getValue();
        return selectedDate.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDateTime();
    }

    // Method to reset the spinner to the current date/time
    public void resetSpinner() {
        LocalDateTime now = LocalDateTime.now();
        Date nowDate = java.sql.Timestamp.valueOf(now);
        spinExpDatetime.setValue(nowDate);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAdv;
    private javax.swing.JButton btnAttach;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRemove;
    private javax.swing.JLabel imageAdvertisement;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAdvName;
    private javax.swing.JLabel lblExpDatetime;
    private javax.swing.JLabel lblLatitude;
    private javax.swing.JLabel lblLongitude;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JSpinner spinExpDatetime;
    private javax.swing.JTextField txtAdvName;
    private javax.swing.JTextField txtLatitude;
    private javax.swing.JTextField txtLongitude;
    // End of variables declaration//GEN-END:variables
}
