/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.AdvertisementAnalystRole;

import static Business.AdvManagement.AdvertisementVisualizations.showBarChart;
import static Business.AdvManagement.AdvertisementVisualizations.showClickTable;
import Business.WorkQueue.AdvertisementWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author kotag
 */
public class AdvertisementAnalystProcessRequestJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    AdvertisementWorkRequest selectedAdvReq;
    LocalDateTime anlTime;

    /**
     * Creates new form AdvertisementAnalystProcessRequestJPanel
     */
    public AdvertisementAnalystProcessRequestJPanel(JPanel userProcessContainer, AdvertisementWorkRequest selectedAdvReq) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.selectedAdvReq = selectedAdvReq;
        
        String output = "";
        int advCount = this.selectedAdvReq.getRequestAdver().getAdvClickCount();
        if (advCount > 0) {
            output = output + "Advertisement Click Count: " + String.valueOf(advCount) + System.lineSeparator();
            output = output + "Clickstream data: " + String.valueOf(this.selectedAdvReq.getRequestAdver().getClickStreamAnalysis()) + System.lineSeparator();
            
            // Top n (Max 5) Customers
            List<Map.Entry<String, Integer>> topCustomers = selectedAdvReq.getRequestAdver().getTop5Customers();
            showBarChart(topCustomers);
            
            this.anlTime = LocalDateTime.now();

            // Click Counts
            Map<String, Integer> clickData = selectedAdvReq.getRequestAdver().getClicksInTimeFrame(this.anlTime );
            showClickTable(clickData);
        } else {
            output = "N/A";
        }
        
        
        txtResult.setText(output);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblResult = new javax.swing.JLabel();
        btnSubmitResult = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResult = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(1000, 650));

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        Title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Title.setText("Process Advertisement Request");

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btnBack)
                .addGap(185, 185, 185)
                .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(296, 296, 296))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Title)
                    .addComponent(btnBack))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        lblResult.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblResult.setText("Result:");

        btnSubmitResult.setBackground(new java.awt.Color(0, 153, 255));
        btnSubmitResult.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnSubmitResult.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmitResult.setText("Submit Result");
        btnSubmitResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitResultActionPerformed(evt);
            }
        });

        txtResult.setColumns(20);
        txtResult.setRows(5);
        jScrollPane1.setViewportView(txtResult);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(lblResult)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSubmitResult)
                .addGap(434, 434, 434))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(lblResult)))
                .addGap(18, 18, 18)
                .addComponent(btnSubmitResult)
                .addContainerGap(182, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.userProcessContainer.remove(this);
        Component[] componentArray = this.userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        AdvertisementAnalystWorkAreaJPanel advertisementAnalystWorkAreaJPanel = (AdvertisementAnalystWorkAreaJPanel) component;
        advertisementAnalystWorkAreaJPanel.populateAdvReqs();
        CardLayout layout = (CardLayout) this.userProcessContainer.getLayout();
        layout.previous(this.userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitResultActionPerformed
        // TODO add your handling code here:
        String resultText = txtResult.getText();
        
        if (resultText.isBlank()) {
            JOptionPane.showMessageDialog(this, "Result cannot be empty.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        this.selectedAdvReq.setResult(resultText);
        this.selectedAdvReq.setWorkStatus("Completed");
        this.selectedAdvReq.setResolutionDate(this.anlTime);
        
        txtResult.setEnabled(false);
        
        JOptionPane.showMessageDialog(this, "Result submitted successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnSubmitResultActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmitResult;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblResult;
    private javax.swing.JTextArea txtResult;
    // End of variables declaration//GEN-END:variables
}
