/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author aakashbelide
 */
public class LoginPageJPanel extends javax.swing.JPanel {
    
    JPanel workAreaJPanel;
    Ecosystem business;

    /**
     * Creates new form LoginPageJPanel
     */
    public LoginPageJPanel(JPanel workAreaJPanel, Ecosystem business) {
        initComponents();
        
        this.workAreaJPanel = workAreaJPanel;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        companyMotto = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnSignup = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        companyMotto.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        companyMotto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        companyMotto.setText("Saving Money and Time for Groceries");

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsername.setText("Username");

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPassword.setText("Password");

        btnLogin.setBackground(new java.awt.Color(0, 153, 255));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnSignup.setBackground(new java.awt.Color(0, 153, 255));
        btnSignup.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSignup.setForeground(new java.awt.Color(255, 255, 255));
        btnSignup.setText("Sign-Up");
        btnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(368, 368, 368)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                        .addComponent(txtUsername)
                        .addComponent(txtPassword)
                        .addComponent(lblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(355, 355, 355))
            .addComponent(companyMotto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(companyMotto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(57, 57, 57)
                .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnLogin)
                .addGap(18, 18, 18)
                .addComponent(btnSignup)
                .addGap(185, 185, 185))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String username = txtUsername.getText();
        char[] passwordCharArray = txtPassword.getPassword();
        String password = String.valueOf(passwordCharArray);
        
        if (username.isBlank() || password.isBlank()) {
            JOptionPane.showMessageDialog(this, "Username and password cannot be empty", "Login error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // 1 - We first check if the user is present in the ecosystem user directory which contains the system admins
        UserAccountDirectory userAccountDirectory = business.getUserAccountDir();
        UserAccount userAccount = userAccountDirectory.userAthentication(username, password);
        
        Network userNetwork= null;
        Enterprise userEnterprise = null;
        Organization userOrg = null;
        
        if (userAccount == null) {
            // 2 - If not found in ecosystem user diretcory, we iterate over each network
            for(Network network : business.getNetworkList()) {
                // 2.1 - In each network, we iterate over each enterprise
                for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                    // 2.2 - In each enterprise, we check if the user is present in the enterprise directory which contains the enterprise admins
                    userAccount = enterprise.getUserAccountDir().userAthentication(username, password);
                    if (userAccount == null) {
                        // 3.1 - If not found in enterprise user diretcory, we iterate over each organization
                        for (Organization organization : enterprise.getOrgDir().getOrgList()) {
                            userAccount = organization.getUserAccountDir().userAthentication(username, password);
                            if (userAccount != null) {
                                // 4 - If the user is found, then we assign the respective values of enterprise and organization for the user
                                userNetwork = network;
                                userEnterprise = enterprise;
                                userOrg = organization;
                                
                                // We break the loop because the user is found
                                break;
                            }
                        }
                    } else {
                        // 3.2 - If the user is found, then we assign the respective value of enterprise and network for the user
                        userEnterprise = enterprise;
                        userNetwork = network;  
                        // We break the loop because the user is found
                        break;
                    }
                    
                    if (userOrg != null) {
                        // We break the loop because the user is found
                        break;
                    }
                }
                
                if (userEnterprise != null) {
                    // We break the loop because the user is found
                    break;
                }
            }
        }
        
        if (userAccount == null) {
            JOptionPane.showMessageDialog(this, "Invalid credentials");
            return;
        } else {
            txtUsername.setText("");
            txtPassword.setText("");
            
            // Whenever the lopgin button is clicked and the user is authenticated, the user is redirected to the respective workArea
            workAreaJPanel.add("WorkArea", userAccount.getUserRole().createWorkArea(workAreaJPanel, business, userNetwork, userEnterprise, userOrg, userAccount));
            CardLayout layout = (CardLayout) workAreaJPanel.getLayout();
            layout.next(workAreaJPanel);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed
        // TODO add your handling code here:
        SignupPageJPanel signupPageJPanel = new SignupPageJPanel(workAreaJPanel, business);
        workAreaJPanel.add("SignupPageJPanel",signupPageJPanel);
        CardLayout layout=(CardLayout) workAreaJPanel.getLayout();
        layout.next(workAreaJPanel);
    }//GEN-LAST:event_btnSignupActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignup;
    private javax.swing.JLabel companyMotto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
