/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.CustomerRole;

import Business.AdvManagement.Advertisement;
import Business.AdvManagement.AdvertisementCatalog;
import Business.AdvManagement.AdvertisementDisplay;
import Business.Enterprise.AdvertisementEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.SuperMarketEnterprise;
import Business.Network.Network;
import Business.ProductManagement.Product;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JPanel;

/**
 *
 * @author aakashbelide
 */
public class CustomerWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Enterprise enterprise;
    Network network;
    UserAccount userAccount;
    Set<String> allProductList = new HashSet<>();
    AdvertisementCatalog custAdvList = new AdvertisementCatalog();
    AdvertisementDisplay adDisplay;
    List<SuperMarketEnterprise> supermarkets = new ArrayList<>();
    int radius = 2;
    
    /**
     * Creates new form CustomerWorkAreaJPanel
     */
    public CustomerWorkAreaJPanel(JPanel userProcessContainer, Network network, Enterprise enterprise, UserAccount userAccount) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.network = network;
        this.userAccount = userAccount;
        
        for (Enterprise enter : this.network.getEnterpriseDirectory().getEnterpriseList()) {
            if (enter.getEnterpriseType() == Enterprise.EnterpriseType.SuperMarket) {
                SuperMarketEnterprise market = (SuperMarketEnterprise) enter;
                if (market.getDistance(this.userAccount.getCustLatLong()) <= radius) {
                    this.supermarkets.add(market);
                    for (Product prod : market.getProductCatalog().getProductList()) {
                        allProductList.add(prod.getProdName());
                    }
                }
            }
            if (enter.getEnterpriseType() == Enterprise.EnterpriseType.Advertisement) {
                AdvertisementEnterprise adEnter = (AdvertisementEnterprise) enter;
                //System.out.println(adEnter.getOrgName());
                //System.out.println(adEnter.getAdvertisementCatalog().getAdvertisementList().size());
                //System.out.println(adEnter.getAdvertisementCatalog().getActiveAdverList().size());
                
                // TO-DO: Replace getActiveAdverList with getActiveRadiusAdverList(LatLong custLatLong, double radius) by passing the custome latlong and the radius
                for (Advertisement activeAdv : adEnter.getAdvertisementCatalog().getActiveRadiusAdverList(userAccount.getCustLatLong(), 2)) {
                    this.custAdvList.appendAdvertisement(activeAdv);
                }
//                for (Advertisement activeAdv : adEnter.getAdvertisementCatalog().getActiveAdverList()) {
//                    this.custAdvList.appendAdvertisement(activeAdv);
//                }
            }
        }
        
        // Initialize and start the AdvertisementDisplay thread
        adDisplay = new AdvertisementDisplay(this.custAdvList, imageAdvertisement, this.userAccount.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        btnSmartShop = new javax.swing.JButton();
        btnShop = new javax.swing.JButton();
        btnViewOrders = new javax.swing.JButton();
        imageAdvertisement = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1000, 650));

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        Title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText(" Welcome!!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogout)
                    .addComponent(Title))
                .addGap(38, 38, 38))
        );

        btnSmartShop.setBackground(new java.awt.Color(0, 153, 255));
        btnSmartShop.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnSmartShop.setForeground(new java.awt.Color(255, 255, 255));
        btnSmartShop.setText("Smart Shopping");
        btnSmartShop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmartShopActionPerformed(evt);
            }
        });

        btnShop.setBackground(new java.awt.Color(0, 153, 255));
        btnShop.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnShop.setForeground(new java.awt.Color(255, 255, 255));
        btnShop.setText("Start Shopping");
        btnShop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShopActionPerformed(evt);
            }
        });

        btnViewOrders.setBackground(new java.awt.Color(0, 153, 255));
        btnViewOrders.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnViewOrders.setForeground(new java.awt.Color(255, 255, 255));
        btnViewOrders.setText("View Orders");
        btnViewOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewOrdersActionPerformed(evt);
            }
        });

        imageAdvertisement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageAdvertisement.setText("<Advertisement>");
        imageAdvertisement.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSmartShop, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnShop, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(279, 279, 279)
                .addComponent(imageAdvertisement, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(imageAdvertisement, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                        .addGap(104, 104, 104))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(btnSmartShop)
                        .addGap(18, 18, 18)
                        .addComponent(btnShop)
                        .addGap(18, 18, 18)
                        .addComponent(btnViewOrders)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        this.userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) this.userProcessContainer.getLayout();
        layout.previous(this.userProcessContainer);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnSmartShopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmartShopActionPerformed
        // TODO add your handling code here:
        CustomerCartJPanel customerCartJPanel = new CustomerCartJPanel(this.userProcessContainer,this.supermarkets, this.allProductList, this.userAccount, this.custAdvList);
        this.userProcessContainer.add("CustomerCartJPanel",customerCartJPanel);
        CardLayout layout=(CardLayout)this.userProcessContainer.getLayout();
        layout.next(this.userProcessContainer);
    }//GEN-LAST:event_btnSmartShopActionPerformed

    private void btnViewOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewOrdersActionPerformed
        // TODO add your handling code here:
//        CustomerCartJPanel customerCartJPanel = new CustomerCartJPanel(this.userProcessContainer, this.enterprise, selectedAdv, this.userAccount);
//        this.userProcessContainer.add("CustomerCartJPanel",customerCartJPanel);
//        CardLayout layout=(CardLayout)this.userProcessContainer.getLayout();
//        layout.next(this.userProcessContainer);
    }//GEN-LAST:event_btnViewOrdersActionPerformed

    private void btnShopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShopActionPerformed
        // TODO add your handling code here:
//        CustomerCartJPanel customerCartJPanel = new CustomerCartJPanel(this.userProcessContainer, this.enterprise, selectedAdv, this.userAccount);
//        this.userProcessContainer.add("CustomerCartJPanel",customerCartJPanel);
//        CardLayout layout=(CardLayout)this.userProcessContainer.getLayout();
//        layout.next(this.userProcessContainer);
    }//GEN-LAST:event_btnShopActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnShop;
    private javax.swing.JButton btnSmartShop;
    private javax.swing.JButton btnViewOrders;
    private javax.swing.JLabel imageAdvertisement;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
