/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.SupplierStockManagerRole;

import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import ui.SuperMarketStockManagerRole.ViewSupplierReqJPanel;

/**
 *
 * @author aakashbelide
 */
public class ViewMarketRequestsJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    Network network;
    UserAccount userAccount;

    /**
     * Creates new form ViewMarketRequestsJPanel
     */
    public ViewMarketRequestsJPanel(JPanel userProcessContainer, Network network, UserAccount userAccount) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.network = network;
        this.userAccount = userAccount;
        
        populateMarketReqs();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMarketReqs = new javax.swing.JTable();
        btnViewMarketReq = new javax.swing.JButton();
        btnAssignMe = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        Title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Market Requests");

        btnBack.setBackground(new java.awt.Color(0, 153, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/arrow.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btnBack)
                .addGap(276, 276, 276)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(451, 451, 451))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Title)
                    .addComponent(btnBack))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        tblMarketReqs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Sender", "Receiver", "Market", "Message", "Status", "Initiated Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMarketReqs);

        btnViewMarketReq.setBackground(new java.awt.Color(0, 153, 255));
        btnViewMarketReq.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnViewMarketReq.setForeground(new java.awt.Color(255, 255, 255));
        btnViewMarketReq.setText("View Market Request");
        btnViewMarketReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMarketReqActionPerformed(evt);
            }
        });

        btnAssignMe.setBackground(new java.awt.Color(0, 153, 255));
        btnAssignMe.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnAssignMe.setForeground(new java.awt.Color(255, 255, 255));
        btnAssignMe.setText("Assign to Myself");
        btnAssignMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignMeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAssignMe)
                        .addGap(18, 18, 18)
                        .addComponent(btnViewMarketReq))
                    .addComponent(jScrollPane1))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewMarketReq)
                    .addComponent(btnAssignMe))
                .addGap(94, 94, 94))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) this.userProcessContainer.getLayout();
        layout.previous(this.userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewMarketReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMarketReqActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblMarketReqs.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a request first.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        WorkRequest selectedWorkRequest = (WorkRequest) tblMarketReqs.getValueAt(selectedRowIndex, 3);

        if (selectedWorkRequest.getReceiver() != this.userAccount) {
            JOptionPane.showMessageDialog(this, "Assign the request to yourself first.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (selectedWorkRequest.getWorkStatus().equalsIgnoreCase("Completed")) {
            JOptionPane.showMessageDialog(this, "Request already completed.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        ProcessMarketRequestJPanel processMarketRequestJPanel = new ProcessMarketRequestJPanel(this.userProcessContainer, selectedWorkRequest);
        this.userProcessContainer.add("ProcessMarketRequestJPanel",processMarketRequestJPanel);
        CardLayout layout=(CardLayout)this.userProcessContainer.getLayout();
        layout.next(this.userProcessContainer);
    }//GEN-LAST:event_btnViewMarketReqActionPerformed

    private void btnAssignMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignMeActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblMarketReqs.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a request first.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        WorkRequest selectedWorkRequest = (WorkRequest) tblMarketReqs.getValueAt(selectedRowIndex, 3);

        if (selectedWorkRequest.getWorkStatus().equalsIgnoreCase("Completed")) {
            JOptionPane.showMessageDialog(this, "Request already completed.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        selectedWorkRequest.setReceiver(this.userAccount);

        JOptionPane.showMessageDialog(this, "Assigned the request to you.", "Success", JOptionPane.INFORMATION_MESSAGE);
        populateMarketReqs();
    }//GEN-LAST:event_btnAssignMeActionPerformed

    public void populateMarketReqs() {
        DefaultTableModel model = (DefaultTableModel) tblMarketReqs.getModel();
        model.setRowCount(0);
        
        for (Enterprise enterprise : this.network.getEnterpriseDirectory().getEnterpriseList()) {
            if (enterprise.getEnterpriseType() == Enterprise.EnterpriseType.SuperMarket) {
                for (WorkRequest workRequest : enterprise.getWorkQueue().getWorkQueue()){
                    Object[] row = new Object[6];
                    row[0] = workRequest.getSender();
                    row[1] = workRequest.getReceiver();
                    row[2] = workRequest.getRequestedDate();
                    row[3] = workRequest;
                    row[4] = workRequest.getWorkStatus();
                    row[5] = enterprise.getOrgName();
                    model.addRow(row);
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JButton btnAssignMe;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnViewMarketReq;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMarketReqs;
    // End of variables declaration//GEN-END:variables
}
