/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.SupplierStockManagerRole;

import Business.Enterprise.SupplierEnterprise;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aakashbelide
 */
public class ViewSupplierRequestsJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    SupplierEnterprise enterprise;
    UserAccount userAccount;

    /**
     * Creates new form ViewSupplierRequestsJPanel
     */
    public ViewSupplierRequestsJPanel(JPanel userProcessContainer, SupplierEnterprise enterprise, UserAccount userAccount) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        
        populateReqs();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSupplierReqs = new javax.swing.JTable();
        btnViewSupReq = new javax.swing.JButton();
        btnCreateReq = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        Title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Title.setText("Supplier Requests");

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Title)
                .addGap(394, 394, 394))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Title)
                    .addComponent(btnBack))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        tblSupplierReqs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Sender", "Receiver", "Initiated Date", "Message", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSupplierReqs);

        btnViewSupReq.setBackground(new java.awt.Color(0, 153, 255));
        btnViewSupReq.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnViewSupReq.setForeground(new java.awt.Color(255, 255, 255));
        btnViewSupReq.setText("View Supplier Request");
        btnViewSupReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewSupReqActionPerformed(evt);
            }
        });

        btnCreateReq.setBackground(new java.awt.Color(0, 153, 255));
        btnCreateReq.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnCreateReq.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateReq.setText("Create Request");
        btnCreateReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateReqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCreateReq)
                        .addGap(18, 18, 18)
                        .addComponent(btnViewSupReq))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 923, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewSupReq)
                    .addComponent(btnCreateReq))
                .addContainerGap(100, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) this.userProcessContainer.getLayout();
        layout.previous(this.userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewSupReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSupReqActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblSupplierReqs.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a request first.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // This is an advertisement request from advertisement workqueue catalog
        WorkRequest selectedReq = (WorkRequest) tblSupplierReqs.getValueAt(selectedRowIndex, 3);

        if (selectedReq.getWorkStatus().equalsIgnoreCase("Pending")) {
            JOptionPane.showMessageDialog(this, "You can view the request once status is completed.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        ViewSupplierReqJPanel viewSupplierReqJPanel = new ViewSupplierReqJPanel(this.userProcessContainer, selectedReq);
        this.userProcessContainer.add("ViewSupplierReqJPanel",viewSupplierReqJPanel);
        CardLayout layout=(CardLayout)this.userProcessContainer.getLayout();
        layout.next(this.userProcessContainer);
    }//GEN-LAST:event_btnViewSupReqActionPerformed

    private void btnCreateReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateReqActionPerformed
        // TODO add your handling code here:
        CreateSupplierRequestJPanel createSupplierRequestJPanel = new CreateSupplierRequestJPanel(this.userProcessContainer, this.enterprise, this.userAccount);
        this.userProcessContainer.add("CreateSupplierRequestJPanel",createSupplierRequestJPanel);
        CardLayout layout=(CardLayout)this.userProcessContainer.getLayout();
        layout.next(this.userProcessContainer);
    }//GEN-LAST:event_btnCreateReqActionPerformed

        public void populateReqs() {
        DefaultTableModel model = (DefaultTableModel) tblSupplierReqs.getModel();
        model.setRowCount(0);

        for (WorkRequest workReq : this.userAccount.getWorkQueue().getWorkQueue()) {
            Object row[] = new Object[5];
            row[0] = workReq.getSender();
            row[1] = workReq.getReceiver();
            row[2] = workReq.getRequestedDate();
            row[3] = workReq;
            row[4] = workReq.getWorkStatus();
            model.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateReq;
    private javax.swing.JButton btnViewSupReq;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSupplierReqs;
    // End of variables declaration//GEN-END:variables
}
