/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.SuperMarketStockManagerRole;

import Business.Enterprise.SuperMarketEnterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Aishwarya
 */
public class SuperMarketStockManagerWorkAreaJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Network network;
    SuperMarketEnterprise enterprise;
    Organization org;
    UserAccount userAccount;

    /**
     * Creates new form SuperMarketStockManagerWorkAreaJPanel
     */
    public SuperMarketStockManagerWorkAreaJPanel(JPanel userProcessContainer, Network network, SuperMarketEnterprise enterprise, Organization org, UserAccount userAccount) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.network = network;
        this.enterprise = enterprise;
        this.org = org;
        this.userAccount = userAccount;
        
        lbltitle.setText(this.enterprise.getOrgName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbltitle = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnMngStock = new javax.swing.JButton();
        btnViewStkCatalog = new javax.swing.JButton();
        btnViewMarket = new javax.swing.JButton();
        btnViewSupReqs = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 102));

        lbltitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbltitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitle.setText("WELCOME");

        btnLogout.setBackground(new java.awt.Color(0, 153, 255));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/power-off.png"))); // NOI18N
        btnLogout.setBorder(null);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(lbltitle, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                .addGap(163, 163, 163)
                .addComponent(btnLogout)
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLogout)
                    .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Supermarket workers-pana.png"))); // NOI18N

        btnMngStock.setBackground(new java.awt.Color(0, 153, 255));
        btnMngStock.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnMngStock.setForeground(new java.awt.Color(255, 255, 255));
        btnMngStock.setText("Manage Stock");
        btnMngStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngStockActionPerformed(evt);
            }
        });

        btnViewStkCatalog.setBackground(new java.awt.Color(0, 153, 255));
        btnViewStkCatalog.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnViewStkCatalog.setForeground(new java.awt.Color(255, 255, 255));
        btnViewStkCatalog.setText("View Stock Catalog");
        btnViewStkCatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewStkCatalogActionPerformed(evt);
            }
        });

        btnViewMarket.setBackground(new java.awt.Color(0, 153, 255));
        btnViewMarket.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnViewMarket.setForeground(new java.awt.Color(255, 255, 255));
        btnViewMarket.setText("View Market Details");
        btnViewMarket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMarketActionPerformed(evt);
            }
        });

        btnViewSupReqs.setBackground(new java.awt.Color(0, 153, 255));
        btnViewSupReqs.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnViewSupReqs.setForeground(new java.awt.Color(255, 255, 255));
        btnViewSupReqs.setText("View Supplier Requests");
        btnViewSupReqs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewSupReqsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jLabel1)
                .addGap(156, 156, 156)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnViewSupReqs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewMarket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewStkCatalog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMngStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(165, 165, 165))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(btnMngStock)
                        .addGap(18, 18, 18)
                        .addComponent(btnViewStkCatalog)
                        .addGap(18, 18, 18)
                        .addComponent(btnViewMarket)
                        .addGap(18, 18, 18)
                        .addComponent(btnViewSupReqs)))
                .addContainerGap(146, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnMngStock, btnViewStkCatalog});

    }// </editor-fold>//GEN-END:initComponents

    private void btnMngStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngStockActionPerformed
        // TODO add your handling code here:
        ManageStockJPanel manageStockJPanel = new ManageStockJPanel(this.userProcessContainer, this.network, this.enterprise.getProductCatalog());
        this.userProcessContainer.add("ManageStockJPanel",manageStockJPanel);
        CardLayout layout=(CardLayout)this.userProcessContainer.getLayout();
        layout.next(this.userProcessContainer);
    }//GEN-LAST:event_btnMngStockActionPerformed

    private void btnViewStkCatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewStkCatalogActionPerformed
        // TODO add your handling code here:
        ViewProductCatalogJPanel viewProductCatalogJPanel = new ViewProductCatalogJPanel(this.userProcessContainer, this.enterprise.getProductCatalog());
        this.userProcessContainer.add("ViewProductCatalogJPanel",viewProductCatalogJPanel);
        CardLayout layout=(CardLayout)this.userProcessContainer.getLayout();
        layout.next(this.userProcessContainer);
    }//GEN-LAST:event_btnViewStkCatalogActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        this.userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) this.userProcessContainer.getLayout();
        layout.previous(this.userProcessContainer);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnViewMarketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMarketActionPerformed
        // TODO add your handling code here:
        ViewMarketJPanel viewMarketJPanel = new ViewMarketJPanel(this.userProcessContainer, this.enterprise);
        this.userProcessContainer.add("ViewMarketJPanel",viewMarketJPanel);
        CardLayout layout=(CardLayout)this.userProcessContainer.getLayout();
        layout.next(this.userProcessContainer);
    }//GEN-LAST:event_btnViewMarketActionPerformed

    private void btnViewSupReqsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSupReqsActionPerformed
        // TODO add your handling code here:
        ViewSupplierRequestsJPanel viewSupplierRequestsJPanel = new ViewSupplierRequestsJPanel(this.userProcessContainer, this.enterprise, this.userAccount);
        this.userProcessContainer.add("ViewSupplierRequestsJPanel",viewSupplierRequestsJPanel);
        CardLayout layout=(CardLayout)this.userProcessContainer.getLayout();
        layout.next(this.userProcessContainer);
    }//GEN-LAST:event_btnViewSupReqsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMngStock;
    private javax.swing.JButton btnViewMarket;
    private javax.swing.JButton btnViewStkCatalog;
    private javax.swing.JButton btnViewSupReqs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbltitle;
    // End of variables declaration//GEN-END:variables
}
