/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.CustomerSupportRole;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CustomerSupportWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author aakashbelide
 */
public class CustomerSupportWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerSupportWorkAreaJPanel
     */
    JPanel userProcessContainer;
    Ecosystem ecosystemBusiness;
    Enterprise enterprise;
    Organization org;
    UserAccount userAccount;
    
    public CustomerSupportWorkAreaJPanel(JPanel userProcessContainer,  Ecosystem ecosystemBusiness, Enterprise enterprise, Organization org, UserAccount userAccount) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.ecosystemBusiness = ecosystemBusiness;
        this.enterprise = enterprise;
        this.org = org;
        this.userAccount = userAccount;
        
         // Get the table header
        JTableHeader header = tblViewCustReq.getTableHeader();
        
        // Customize the header background and text color
        header.setDefaultRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(
                JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                
                JLabel label = (JLabel) super.getTableCellRendererComponent(
                    table, value, isSelected, hasFocus, row, column);
                
                // Set background color
                label.setBackground(new Color(0,153,255)  );
                // Set text color
                label.setForeground(Color.WHITE);
                // Set font style and size
                label.setFont(new Font("Helvetica Neue", Font.BOLD, 14));
                
                return label;
            }
        });
        
        populateCustomerReqs();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        lblEnterpriseNameTitle = new javax.swing.JLabel();
        lblEnterpriseName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewCustReq = new javax.swing.JTable();
        btnAsgnMe = new javax.swing.JButton();
        btnCheckReq = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 102));

        Title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Customer Support Work Area");

        btnLogout.setBackground(new java.awt.Color(0, 153, 255));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/power-off.png"))); // NOI18N
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(372, 372, 372)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                .addGap(199, 199, 199)
                .addComponent(btnLogout)
                .addGap(58, 58, 58))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Title)
                    .addComponent(btnLogout))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        lblEnterpriseNameTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblEnterpriseNameTitle.setText("Enterprise Name:");

        lblEnterpriseName.setText("<enterprise>");

        tblViewCustReq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Order Item", "Item Price", "Item Quantity", "Message", "Sender", "Receiver", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblViewCustReq);

        btnAsgnMe.setBackground(new java.awt.Color(0, 153, 255));
        btnAsgnMe.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnAsgnMe.setForeground(new java.awt.Color(255, 255, 255));
        btnAsgnMe.setText("Assign to Myself");
        btnAsgnMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsgnMeActionPerformed(evt);
            }
        });

        btnCheckReq.setBackground(new java.awt.Color(0, 153, 255));
        btnCheckReq.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnCheckReq.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckReq.setText("Check Request");
        btnCheckReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckReqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(365, 365, 365)
                        .addComponent(lblEnterpriseNameTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEnterpriseName, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(470, 470, 470)
                                .addComponent(btnAsgnMe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(43, 43, 43)
                                .addComponent(btnCheckReq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))))
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnterpriseNameTitle)
                    .addComponent(lblEnterpriseName))
                .addGap(69, 69, 69)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAsgnMe)
                    .addComponent(btnCheckReq))
                .addGap(70, 70, 70))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        this.userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) this.userProcessContainer.getLayout();
        layout.previous(this.userProcessContainer);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAsgnMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsgnMeActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblViewCustReq.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a request first.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // This is an advertisement request from advertisement workqueue catalog
        CustomerSupportWorkRequest selectedCustReq = (CustomerSupportWorkRequest) tblViewCustReq.getValueAt(selectedRowIndex, 3);

        selectedCustReq.setReceiver(this.userAccount);

        JOptionPane.showMessageDialog(this, "Assigned the request to you.", "Success", JOptionPane.INFORMATION_MESSAGE);
        populateCustomerReqs();
    }//GEN-LAST:event_btnAsgnMeActionPerformed

    private void btnCheckReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckReqActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblViewCustReq.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a request first.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // This is an advertisement request from advertisement workqueue catalog
        CustomerSupportWorkRequest selectedCustReq = (CustomerSupportWorkRequest) tblViewCustReq.getValueAt(selectedRowIndex, 3);

        if (selectedCustReq.getReceiver() != this.userAccount) {
            JOptionPane.showMessageDialog(this, "Assign the request to yourself first.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (selectedCustReq.getWorkStatus().equalsIgnoreCase("Completed")) {
            JOptionPane.showMessageDialog(this, "Request already completed.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        CustomerSupportProcessRequestJPanel customerSupportProcessRequestJPanel = new CustomerSupportProcessRequestJPanel(this.userProcessContainer, selectedCustReq);
        this.userProcessContainer.add("CustomerSupportProcessRequestJPanel",customerSupportProcessRequestJPanel);
        CardLayout layout=(CardLayout)this.userProcessContainer.getLayout();
        layout.next(this.userProcessContainer);
    }//GEN-LAST:event_btnCheckReqActionPerformed

    public void populateCustomerReqs() {
        DefaultTableModel model = (DefaultTableModel) tblViewCustReq.getModel();
        model.setRowCount(0);

        for (WorkRequest workReq : this.userAccount.getWorkQueue().getWorkQueue()) {
            CustomerSupportWorkRequest custWorkReq = (CustomerSupportWorkRequest) workReq;
            Object row[] = new Object[7];
            row[0] = custWorkReq.getReqOrderItem();
            row[1] = custWorkReq.getReqOrderItem().getBuyPrice();
            row[2] = custWorkReq.getReqOrderItem().getItemQuant();
            row[3] = custWorkReq;
            row[4] = custWorkReq.getSender();
            row[5] = custWorkReq.getReceiver();
            row[6] = custWorkReq.getWorkStatus();
            model.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JButton btnAsgnMe;
    private javax.swing.JButton btnCheckReq;
    private javax.swing.JButton btnLogout;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEnterpriseName;
    private javax.swing.JLabel lblEnterpriseNameTitle;
    private javax.swing.JTable tblViewCustReq;
    // End of variables declaration//GEN-END:variables
}
