/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ProductManagerRole;

import Business.Enterprise.SupplierEnterprise;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aakashbelide
 */
public class ViewSupplierRequestsJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    SupplierEnterprise enterprise;
    UserAccount userAccount;

    /**
     * Creates new form ViewSupplierRequestsJPanel
     */
    public ViewSupplierRequestsJPanel(JPanel userProcessContainer, SupplierEnterprise enterprise, UserAccount userAccount) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        
        populateSupReqs();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSupplierReqs = new javax.swing.JTable();
        btnViewSupReq = new javax.swing.JButton();
        btnAssignMe = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        Title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Supplier Requests");

        btnBack.setBackground(new java.awt.Color(0, 153, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/arrow.png"))); // NOI18N
        btnBack.setBorder(null);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btnBack)
                .addGap(320, 320, 320)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                .addGap(394, 394, 394))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Title)
                    .addComponent(btnBack))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        tblSupplierReqs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Sender", "Receiver", "Initiated Date", "Message", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSupplierReqs);

        btnViewSupReq.setBackground(new java.awt.Color(0, 153, 255));
        btnViewSupReq.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnViewSupReq.setForeground(new java.awt.Color(255, 255, 255));
        btnViewSupReq.setText("View Supplier Request");
        btnViewSupReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewSupReqActionPerformed(evt);
            }
        });

        btnAssignMe.setBackground(new java.awt.Color(0, 153, 255));
        btnAssignMe.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnAssignMe.setForeground(new java.awt.Color(255, 255, 255));
        btnAssignMe.setText("Assign to Myself");
        btnAssignMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignMeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(569, 569, 569)
                        .addComponent(btnAssignMe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnViewSupReq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewSupReq)
                    .addComponent(btnAssignMe))
                .addGap(95, 95, 95))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) this.userProcessContainer.getLayout();
        layout.previous(this.userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewSupReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSupReqActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblSupplierReqs.getSelectedRow();
        
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a request first.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        WorkRequest selectedWorkRequest = (WorkRequest) tblSupplierReqs.getValueAt(selectedRowIndex, 3);
        
        if (selectedWorkRequest.getReceiver() != this.userAccount) {
            JOptionPane.showMessageDialog(this, "Assign the request to yourself first.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (selectedWorkRequest.getWorkStatus().equalsIgnoreCase("Completed")) {
            JOptionPane.showMessageDialog(this, "Request already completed.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        ProcessSupplierRequestJPanel processSupplierRequestJPanel = new ProcessSupplierRequestJPanel(this.userProcessContainer, selectedWorkRequest);
        this.userProcessContainer.add("ProcessSupplierRequestJPanel",processSupplierRequestJPanel);
        CardLayout layout=(CardLayout)this.userProcessContainer.getLayout();
        layout.next(this.userProcessContainer);
    }//GEN-LAST:event_btnViewSupReqActionPerformed

    private void btnAssignMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignMeActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblSupplierReqs.getSelectedRow();
        
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a request first.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        WorkRequest selectedWorkRequest = (WorkRequest) tblSupplierReqs.getValueAt(selectedRowIndex, 3);
        
        if (selectedWorkRequest.getWorkStatus().equalsIgnoreCase("Completed")) {
            JOptionPane.showMessageDialog(this, "Request already completed.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        selectedWorkRequest.setReceiver(this.userAccount);
        
        JOptionPane.showMessageDialog(this, "Assigned the request to you.", "Success", JOptionPane.INFORMATION_MESSAGE);
        populateSupReqs();
    }//GEN-LAST:event_btnAssignMeActionPerformed

    public void populateSupReqs() {
        DefaultTableModel model = (DefaultTableModel) tblSupplierReqs.getModel();
        model.setRowCount(0);
        
        for (WorkRequest workRequest : this.enterprise.getWorkQueue().getWorkQueue()){
            Object[] row = new Object[5];
            row[0] = workRequest.getSender();
            row[1] = workRequest.getReceiver();
            row[2] = workRequest.getRequestedDate();
            row[3] = workRequest;
            row[4] = workRequest.getWorkStatus();
            model.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JButton btnAssignMe;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnViewSupReq;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSupplierReqs;
    // End of variables declaration//GEN-END:variables
}
