/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.CustomerRole;

import Business.AdvManagement.Advertisement;
import Business.AdvManagement.AdvertisementCatalog;
import Business.AdvManagement.AdvertisementDisplay;
import Business.Enterprise.AdvertisementEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.SuperMarketEnterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.ProductManagement.Product;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JPanel;

/**
 *
 * @author aakashbelide
 */
public class CustomerWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Enterprise enterprise;
    Network network;
    Organization org;
    UserAccount userAccount;
    Set<String> allProductList = new HashSet<>();
    AdvertisementCatalog custAdvList = new AdvertisementCatalog();
    AdvertisementDisplay adDisplay;
    List<SuperMarketEnterprise> nearBySupermarkets = new ArrayList<>();
    List<SuperMarketEnterprise> allSupermarkets = new ArrayList<>();
    int radius = 2;
    
    /**
     * Creates new form CustomerWorkAreaJPanel
     */
    public CustomerWorkAreaJPanel(JPanel userProcessContainer, Network network, Enterprise enterprise, Organization org, UserAccount userAccount) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.network = network;
        this.org = org;
        this.userAccount = userAccount;
        
        for (Enterprise enter : this.network.getEnterpriseDirectory().getEnterpriseList()) {
            if (enter.getEnterpriseType() == Enterprise.EnterpriseType.SuperMarket) {
                SuperMarketEnterprise market = (SuperMarketEnterprise) enter;
                if (market.getDistance(this.userAccount.getCustLatLong()) <= radius) {
                    this.nearBySupermarkets.add(market);
                    for (Product prod : market.getProductCatalog().getProductList()) {
                        allProductList.add(prod.getProdName());
                    }
                }
                // List of all super markets in the network
                allSupermarkets.add(market);
            }
            if (enter.getEnterpriseType() == Enterprise.EnterpriseType.Advertisement) {
                AdvertisementEnterprise adEnter = (AdvertisementEnterprise) enter;
                //System.out.println(adEnter.getOrgName());
                //System.out.println(adEnter.getAdvertisementCatalog().getAdvertisementList().size());
                //System.out.println(adEnter.getAdvertisementCatalog().getActiveAdverList().size());
                
                // TO-DO: Replace getActiveAdverList with getActiveRadiusAdverList(LatLong custLatLong, double radius) by passing the custome latlong and the radius
                for (Advertisement activeAdv : adEnter.getAdvertisementCatalog().getActiveRadiusAdverList(userAccount.getCustLatLong(), 2)) {
                    this.custAdvList.appendAdvertisement(activeAdv);
                }
                //for (Advertisement activeAdv : adEnter.getAdvertisementCatalog().getActiveAdverList()) {
                //    this.custAdvList.appendAdvertisement(activeAdv);
                //}
            }
        }
        
        // Start the advertisements
        startAdv();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        btnSmartShop = new javax.swing.JButton();
        btnShop = new javax.swing.JButton();
        btnViewOrders = new javax.swing.JButton();
        btnViewProfile = new javax.swing.JButton();
        imageAdvertisement = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1000, 650));

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        btnLogout.setBackground(new java.awt.Color(0, 153, 255));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/power-off.png"))); // NOI18N
        btnLogout.setBorder(null);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        Title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText(" Welcome!!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
                .addGap(101, 101, 101)
                .addComponent(btnLogout)
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogout)
                    .addComponent(Title))
                .addGap(38, 38, 38))
        );

        btnSmartShop.setBackground(new java.awt.Color(0, 153, 255));
        btnSmartShop.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnSmartShop.setForeground(new java.awt.Color(255, 255, 255));
        btnSmartShop.setText("Smart Shopping");
        btnSmartShop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmartShopActionPerformed(evt);
            }
        });

        btnShop.setBackground(new java.awt.Color(0, 153, 255));
        btnShop.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnShop.setForeground(new java.awt.Color(255, 255, 255));
        btnShop.setText("Start Shopping");
        btnShop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShopActionPerformed(evt);
            }
        });

        btnViewOrders.setBackground(new java.awt.Color(0, 153, 255));
        btnViewOrders.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnViewOrders.setForeground(new java.awt.Color(255, 255, 255));
        btnViewOrders.setText("View Orders");
        btnViewOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewOrdersActionPerformed(evt);
            }
        });

        btnViewProfile.setBackground(new java.awt.Color(0, 153, 255));
        btnViewProfile.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnViewProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnViewProfile.setText("View Profile");
        btnViewProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewProfileActionPerformed(evt);
            }
        });

        imageAdvertisement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageAdvertisement.setText("<Advertisement>");
        imageAdvertisement.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fruit shop-rafiki.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1)
                .addGap(123, 123, 123)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSmartShop, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(btnShop, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(btnViewOrders, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(btnViewProfile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addGap(183, 183, 183)
                .addComponent(imageAdvertisement, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(imageAdvertisement, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                        .addGap(104, 104, 104))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(195, 195, 195)
                                .addComponent(btnSmartShop)
                                .addGap(18, 18, 18)
                                .addComponent(btnShop)
                                .addGap(18, 18, 18)
                                .addComponent(btnViewOrders)
                                .addGap(18, 18, 18)
                                .addComponent(btnViewProfile))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(jLabel1)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        // Stop the advertisements
        stopAdv();
        
        this.userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) this.userProcessContainer.getLayout();
        layout.previous(this.userProcessContainer);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnSmartShopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmartShopActionPerformed
        // TODO add your handling code here:
        // Stop the advertisements
        stopAdv();
        
        SmartShoppingJPanel customerCartJPanel = new SmartShoppingJPanel(this.userProcessContainer,this.nearBySupermarkets, this.allProductList, this.userAccount, this.custAdvList);
        this.userProcessContainer.add("CustomerCartJPanel",customerCartJPanel);
        CardLayout layout=(CardLayout)this.userProcessContainer.getLayout();
        layout.next(this.userProcessContainer);
    }//GEN-LAST:event_btnSmartShopActionPerformed

    private void btnViewOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewOrdersActionPerformed
        // TODO add your handling code here:
        // Stop the advertisements
        stopAdv();
        
        CustomerOrdersJPanel customerOrdersJPanel = new CustomerOrdersJPanel(this.userProcessContainer, this.userAccount.getCustOrders().getOrders(), this.userAccount, this.custAdvList , this.enterprise);
        this.userProcessContainer.add("CustomerOrdersJPanel",customerOrdersJPanel);
        CardLayout layout=(CardLayout)this.userProcessContainer.getLayout();
        layout.next(this.userProcessContainer);
    }//GEN-LAST:event_btnViewOrdersActionPerformed

    private void btnShopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShopActionPerformed
        // TODO add your handling code here:
        // Stop the advertisements
        stopAdv();
        
        ShoppingJPanel shoppingJPanel = new ShoppingJPanel(this.userProcessContainer, this.allSupermarkets, this.userAccount, this.custAdvList);
        this.userProcessContainer.add("ShoppingJPanel",shoppingJPanel);
        CardLayout layout=(CardLayout)this.userProcessContainer.getLayout();
        layout.next(this.userProcessContainer);
    }//GEN-LAST:event_btnShopActionPerformed

    private void btnViewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProfileActionPerformed
        // TODO add your handling code here:
        // Stop the advertisements
        stopAdv();
        
        ViewProfileJPanel viewProfileJPanel = new ViewProfileJPanel(this.userProcessContainer, this.org, this.userAccount, this.custAdvList);
        this.userProcessContainer.add("ViewProfileJPanel",viewProfileJPanel);
        CardLayout layout=(CardLayout)this.userProcessContainer.getLayout();
        layout.next(this.userProcessContainer);
    }//GEN-LAST:event_btnViewProfileActionPerformed

    public void startAdv() {
        // Initialize and start the AdvertisementDisplay thread
        adDisplay = new AdvertisementDisplay(this.custAdvList, imageAdvertisement, this.userAccount.getUsername());
    }
    
    public void stopAdv() {
        // Stop the running advertisements
        this.adDisplay.stopAdvertisementDisplay();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnShop;
    private javax.swing.JButton btnSmartShop;
    private javax.swing.JButton btnViewOrders;
    private javax.swing.JButton btnViewProfile;
    private javax.swing.JLabel imageAdvertisement;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
