/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.CustomerRole;

import Business.AdvManagement.AdvertisementCatalog;
import Business.AdvManagement.AdvertisementDisplay;
import Business.OrderManagement.OrderItem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author aakashbelide
 */
public class ItemFeedbaackJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    OrderItem selectedOrderItem;
    UserAccount userAccount;
    AdvertisementCatalog custAdvList;
    AdvertisementDisplay adDisplay;

    
     private void resetFields() {
        txtRefundReason.setText(""); // Clear the text area

        // Clear the radio button selection
        ButtonGroup ratingGroup = new ButtonGroup();
        ratingGroup.add(radioBtnRate1);
        ratingGroup.add(radioBtnRate2);
        ratingGroup.add(radioBtnRate3);
        ratingGroup.add(radioBtnRate4);
        ratingGroup.add(radioBtnRate5);
        ratingGroup.clearSelection();
    }
    /**
     * Creates new form ItemFeedbaackJPanel
     */
    public ItemFeedbaackJPanel(JPanel userProcessContainer, OrderItem selectedOrderItem, UserAccount userAccount, AdvertisementCatalog custAdvList) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.selectedOrderItem = selectedOrderItem;
        this.userAccount = userAccount;
        this.custAdvList = custAdvList;
        
        // Start the advertisements
        startAdv();
    // Group radio buttons for the rating system
        groupRadioButtons();
    }

    /**
     * Groups the radio buttons for ratings.
     */
    private void groupRadioButtons() {
        ButtonGroup ratingGroup = new ButtonGroup();
        ratingGroup.add(radioBtnRate1);
        ratingGroup.add(radioBtnRate2);
        ratingGroup.add(radioBtnRate3);
        ratingGroup.add(radioBtnRate4);
        ratingGroup.add(radioBtnRate5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        lblFeedback1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRefundReason = new javax.swing.JTextArea();
        lblFeedback = new javax.swing.JLabel();
        radioBtnRate1 = new javax.swing.JRadioButton();
        radioBtnRate2 = new javax.swing.JRadioButton();
        radioBtnRate3 = new javax.swing.JRadioButton();
        radioBtnRate4 = new javax.swing.JRadioButton();
        radioBtnRate5 = new javax.swing.JRadioButton();
        btnPostFeedback = new javax.swing.JButton();
        imageAdvertisement = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        btnBack.setBackground(new java.awt.Color(0, 153, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/arrow.png"))); // NOI18N
        btnBack.setBorder(null);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        Title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Give Feedback");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(201, 201, 201))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(Title))
                .addGap(38, 38, 38))
        );

        lblFeedback1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblFeedback1.setText("Feedback:");

        txtRefundReason.setColumns(20);
        txtRefundReason.setRows(5);
        jScrollPane1.setViewportView(txtRefundReason);

        lblFeedback.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblFeedback.setText("Rating:");

        radioBtnRate1.setText("1");

        radioBtnRate2.setText("2");

        radioBtnRate3.setText("3");

        radioBtnRate4.setText("4");

        radioBtnRate5.setText("5");

        btnPostFeedback.setBackground(new java.awt.Color(0, 153, 255));
        btnPostFeedback.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnPostFeedback.setForeground(new java.awt.Color(255, 255, 255));
        btnPostFeedback.setText("Post Feedback");
        btnPostFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostFeedbackActionPerformed(evt);
            }
        });

        imageAdvertisement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageAdvertisement.setText("<Advertisement>");
        imageAdvertisement.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFeedback1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFeedback)
                                .addGap(33, 33, 33)
                                .addComponent(radioBtnRate1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioBtnRate2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioBtnRate3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioBtnRate4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioBtnRate5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(btnPostFeedback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(10, 10, 10)))
                        .addGap(20, 20, 20)))
                .addGap(232, 232, 232)
                .addComponent(imageAdvertisement, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(imageAdvertisement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(107, 107, 107))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(lblFeedback1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(53, 53, 53)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblFeedback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(radioBtnRate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(radioBtnRate2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(radioBtnRate3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(radioBtnRate4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(radioBtnRate5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(btnPostFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(218, 218, 218))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        // Stop the advertisements
        stopAdv();
        
        this.userProcessContainer.remove(this);
        Component[] componentArray = this.userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ViewOrderJPanel viewOrderJPanel = (ViewOrderJPanel) component;
        viewOrderJPanel.startAdv();
        CardLayout layout = (CardLayout) this.userProcessContainer.getLayout();
        layout.previous(this.userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnPostFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostFeedbackActionPerformed
        // TODO add your handling code here:
        //TO-DO: Update feedback and rating for the selected orderitem, if already present, then show it.
       if (txtRefundReason.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Feedback should not be empty!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Check if any rating is selected
    if (!(radioBtnRate1.isSelected() || radioBtnRate2.isSelected() || 
          radioBtnRate3.isSelected() || radioBtnRate4.isSelected() || radioBtnRate5.isSelected())) {
        JOptionPane.showMessageDialog(this, "Please select a rating!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // If validation passes, display success message
    JOptionPane.showMessageDialog(this, "Feedback submitted successfully!");

    // Reset the feedback fields
    resetFields(); // Clear the radio button selection
    }//GEN-LAST:event_btnPostFeedbackActionPerformed

    public void startAdv() {
        // Initialize and start the AdvertisementDisplay thread
        adDisplay = new AdvertisementDisplay(this.custAdvList, imageAdvertisement, this.userAccount.getUsername());
    }
    
    public void stopAdv() {
        // Stop the running advertisements
        this.adDisplay.stopAdvertisementDisplay();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnPostFeedback;
    private javax.swing.JLabel imageAdvertisement;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFeedback;
    private javax.swing.JLabel lblFeedback1;
    private javax.swing.JRadioButton radioBtnRate1;
    private javax.swing.JRadioButton radioBtnRate2;
    private javax.swing.JRadioButton radioBtnRate3;
    private javax.swing.JRadioButton radioBtnRate4;
    private javax.swing.JRadioButton radioBtnRate5;
    private javax.swing.JTextArea txtRefundReason;
    // End of variables declaration//GEN-END:variables
}
