/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.CustomerRole;

import Business.AdvManagement.AdvertisementCatalog;
import Business.AdvManagement.AdvertisementDisplay;
import static Business.OrderManagement.Mailer.sendEmail;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author aakashbelide
 */
public class ViewProfileJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    Organization org;
    UserAccount userAccount;
    AdvertisementCatalog custAdvList;
    AdvertisementDisplay adDisplay;

    /**
     * Creates new form ViewProfileJPanel
     */
    public ViewProfileJPanel(JPanel userProcessContainer, Organization org, UserAccount userAccount, AdvertisementCatalog custAdvList) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.org = org;
        this.userAccount = userAccount;
        this.custAdvList = custAdvList;
        
        // Start the advertisements
        startAdv();
        
        txtName.setText(this.userAccount.getPerson().getPersonName());
        txtEmail.setText(this.userAccount.getUsername());
        txtLat.setText(String.valueOf(this.userAccount.getCustLatLong().getLatitude()));
        txtLong.setText(String.valueOf(this.userAccount.getCustLatLong().getLongitude()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblLat = new javax.swing.JLabel();
        txtLat = new javax.swing.JTextField();
        lblLong = new javax.swing.JLabel();
        txtLong = new javax.swing.JTextField();
        lblPass = new javax.swing.JLabel();
        pass1 = new javax.swing.JPasswordField();
        lblRePass = new javax.swing.JLabel();
        pass2 = new javax.swing.JPasswordField();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnUpdatePass = new javax.swing.JButton();
        btnSavePass = new javax.swing.JButton();
        imageAdvertisement = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        btnBack.setBackground(new java.awt.Color(0, 153, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/arrow.png"))); // NOI18N
        btnBack.setBorder(null);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        Title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Profile");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(201, 201, 201))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(Title))
                .addGap(38, 38, 38))
        );

        lblName.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblName.setText("Name:");

        txtName.setEnabled(false);

        lblEmail.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblEmail.setText("Email:");

        txtEmail.setEnabled(false);

        lblLat.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblLat.setText("Latitude:");

        txtLat.setEnabled(false);

        lblLong.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblLong.setText("Longitude:");

        txtLong.setEnabled(false);

        lblPass.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblPass.setText("Password:");

        pass1.setEnabled(false);

        lblRePass.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblRePass.setText("Re-type Password:");

        pass2.setEnabled(false);

        btnUpdate.setBackground(new java.awt.Color(0, 153, 255));
        btnUpdate.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(0, 153, 255));
        btnSave.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdatePass.setBackground(new java.awt.Color(0, 153, 255));
        btnUpdatePass.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnUpdatePass.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdatePass.setText("Update Password");
        btnUpdatePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePassActionPerformed(evt);
            }
        });

        btnSavePass.setBackground(new java.awt.Color(0, 153, 255));
        btnSavePass.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnSavePass.setForeground(new java.awt.Color(255, 255, 255));
        btnSavePass.setText("Save Password");
        btnSavePass.setEnabled(false);
        btnSavePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePassActionPerformed(evt);
            }
        });

        imageAdvertisement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageAdvertisement.setText("<Advertisement>");
        imageAdvertisement.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLong, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPass, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLat, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRePass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLong)
                    .addComponent(txtLat)
                    .addComponent(txtEmail)
                    .addComponent(txtName)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pass1)
                    .addComponent(pass2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnUpdatePass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSavePass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(288, 288, 288)
                .addComponent(imageAdvertisement, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(imageAdvertisement, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                        .addGap(107, 107, 107))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLat)
                            .addComponent(txtLat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLong))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPass)
                            .addComponent(pass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRePass)
                            .addComponent(pass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdatePass, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSavePass, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        // Stop the advertisements
        stopAdv();

        this.userProcessContainer.remove(this);
        Component[] componentArray = this.userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CustomerWorkAreaJPanel customerWorkAreaJPanel = (CustomerWorkAreaJPanel) component;
        customerWorkAreaJPanel.startAdv();
        CardLayout layout = (CardLayout) this.userProcessContainer.getLayout();
        layout.previous(this.userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        txtName.setEnabled(true);
        txtEmail.setEnabled(true);
        txtLat.setEnabled(true);
        txtLong.setEnabled(true);
        btnUpdate.setEnabled(false);
        btnSave.setEnabled(true);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String oldEmail = this.userAccount.getUsername();
        String name = txtName.getText();
        String email = txtEmail.getText();
        String lat = txtLat.getText();
        String longi = txtLong.getText();
        
        double dblLat = 0;
        double dblLongi = 0;
        
        if (name.isBlank() || email.isBlank() || lat.isBlank() || longi.isBlank()) {
            JOptionPane.showMessageDialog(this, "All fields are mandatory.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (!checkEmail(email)) {
            JOptionPane.showMessageDialog(this, "Invalid email ID. Please check.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (!this.org.getUserAccountDir().checkIsUsernameUnique(email)) {
            JOptionPane.showMessageDialog(this, "Username already taken. Please provide a different e-mail ID.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            dblLat = Double.parseDouble(lat);
            dblLongi = Double.parseDouble(longi);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Invalid latlong. Latitude and logitude can only be integers or decimals. Please check.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        this.userAccount.getPerson().setPersonName(name);
        this.userAccount.setUsername(email);
        this.userAccount.setCustLatLong(dblLat, dblLongi);
        
        StringBuilder emailBody = new StringBuilder();
        String emailSubject = "Profile updated succesffuly";
        
        emailBody.append("<p>Hi ").append(name).append("!</p>");
        emailBody.append("<p>Your profile has been updated successfully.</p>");
        emailBody.append("<p>This was not you? Update your password.</p>");
        
        //sendEmail("aakashcoolstar12@gmail.com", emailSubject, emailBody.toString());
        sendEmail(email, emailSubject, emailBody.toString());
        sendEmail(oldEmail, emailSubject, emailBody.toString());
        
        JOptionPane.showMessageDialog(this, "Profile updated successfully.", "Warning", JOptionPane.INFORMATION_MESSAGE);
        
        txtName.setEnabled(false);
        txtEmail.setEnabled(false);
        txtLat.setEnabled(false);
        txtLong.setEnabled(false);
        btnUpdate.setEnabled(true);
        btnSave.setEnabled(false);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnSavePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePassActionPerformed
        // TODO add your handling code here:
        char[] passwordCharArray1 = pass1.getPassword();
        String password1 = String.valueOf(passwordCharArray1);
        
        char[] passwordCharArray2 = pass2.getPassword();
        String password2 = String.valueOf(passwordCharArray2);
        
        if (!password1.equals(password2)) {
            JOptionPane.showMessageDialog(this, "Passwords don't match. Please check.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (password1.isBlank() || password2.isBlank()) {
            JOptionPane.showMessageDialog(this, "Passwordcannot be empty.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        this.userAccount.setPassword(password2);
        
        StringBuilder emailBody = new StringBuilder();
        String emailSubject = "Profile updated succesffuly";
        
        emailBody.append("<p>Hi ").append(this.userAccount.getPerson().getPersonName()).append("!</p>");
        emailBody.append("<p>Your password has been updated successfully.</p>");
        emailBody.append("<p>This was not you? Please contact admin.</p>");
        
        //sendEmail("aakashcoolstar12@gmail.com", emailSubject, emailBody.toString());
        sendEmail(this.userAccount.getUsername(), emailSubject, emailBody.toString());
        
        JOptionPane.showMessageDialog(this, "Password updated successfully.", "Warning", JOptionPane.INFORMATION_MESSAGE);
        
        pass1.setEnabled(false);
        pass2.setEnabled(false);
        btnUpdatePass.setEnabled(true);
        btnSavePass.setEnabled(false);
    }//GEN-LAST:event_btnSavePassActionPerformed

    private void btnUpdatePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePassActionPerformed
        // TODO add your handling code here:
        pass1.setEnabled(true);
        pass2.setEnabled(true);
        btnUpdatePass.setEnabled(false);
        btnSavePass.setEnabled(true);
    }//GEN-LAST:event_btnUpdatePassActionPerformed

    public void startAdv() {
        // Initialize and start the AdvertisementDisplay thread
        adDisplay = new AdvertisementDisplay(this.custAdvList, imageAdvertisement, this.userAccount.getUsername());
    }
    
    public void stopAdv() {
        // Stop the running advertisements
        this.adDisplay.stopAdvertisementDisplay();
    }
    
    private Boolean checkEmail(String email) {
        if (email == null || email.isEmpty()) {
            return false; // Email is null or empty
        }

        // Regular expression for validating an email address
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@" +
                            "(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";

        // Compile the regex
        Pattern pattern = Pattern.compile(emailRegex);

        // Match the email against the regex
        return pattern.matcher(email).matches();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSavePass;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdatePass;
    private javax.swing.JLabel imageAdvertisement;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblLat;
    private javax.swing.JLabel lblLong;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblRePass;
    private javax.swing.JPasswordField pass1;
    private javax.swing.JPasswordField pass2;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLat;
    private javax.swing.JTextField txtLong;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
