/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.CustomerRole;

import Business.AdvManagement.AdvertisementCatalog;
import Business.AdvManagement.AdvertisementDisplay;
import Business.Enterprise.SuperMarketEnterprise;
import static Business.OrderManagement.Mailer.sendEmail;
import Business.OrderManagement.Order;
import Business.OrderManagement.OrderItem;
import Business.ProductManagement.Product;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.util.List;
import java.util.Map;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author kotag
 */
public class ViewOrderTotalJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    Map<String, Object> result;
    UserAccount userAccount;
    AdvertisementCatalog custAdvList;
    AdvertisementDisplay adDisplay;

    /**
     * Creates new form ViewOrderTotalJPanel
     */
    public ViewOrderTotalJPanel(JPanel userProcessContainer, Map<String, Object> result, UserAccount userAccount, AdvertisementCatalog custAdvList) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.result = result;
        this.userAccount = userAccount;
        this.custAdvList = custAdvList;
        
        JTableHeader header = tblViewOrder.getTableHeader();
        
        
        // Customize the header background and text color
        header.setDefaultRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(
                JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                
                JLabel label = (JLabel) super.getTableCellRendererComponent(
                    table, value, isSelected, hasFocus, row, column);
                
                // Set background color
                label.setBackground(new Color(0,153,255)  );
                // Set text color
                label.setForeground(Color.WHITE);
                // Set font style and size
                label.setFont(new Font("Helvetica Neue", Font.BOLD, 14));
                
                return label;
            }
        });
        
        // Start the advertisements
        startAdv();
        
        lblOrderTot.setText("$ " + String.valueOf(result.get("totalCost")));
        
        populateOrderTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewOrder = new javax.swing.JTable();
        lblTotOrdAmt = new javax.swing.JLabel();
        lblOrderTot = new javax.swing.JLabel();
        btnPay = new javax.swing.JButton();
        imageAdvertisement = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        btnBack.setBackground(new java.awt.Color(0, 153, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/arrow.png"))); // NOI18N
        btnBack.setBorder(null);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        Title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Confirm Order");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(btnBack)
                .addGap(63, 63, 63)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBack)
                    .addComponent(Title))
                .addGap(38, 38, 38))
        );

        tblViewOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Product Name", "Quantity", "Price", "Market Name", "Total Amount", "Distance"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblViewOrder);

        lblTotOrdAmt.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        lblTotOrdAmt.setText("Total Order Amount :");

        lblOrderTot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrderTot.setText("$ 0");

        btnPay.setBackground(new java.awt.Color(0, 153, 255));
        btnPay.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnPay.setForeground(new java.awt.Color(255, 255, 255));
        btnPay.setText("Pay");
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });

        imageAdvertisement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageAdvertisement.setText("<Advertisement>");
        imageAdvertisement.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(475, 475, 475)
                        .addComponent(lblTotOrdAmt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOrderTot, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addGap(35, 35, 35)
                .addComponent(imageAdvertisement, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageAdvertisement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotOrdAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOrderTot, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addGap(107, 107, 107))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        // Stop the advertisements
        stopAdv();
        
        this.userProcessContainer.remove(this);
        Component[] componentArray = this.userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SmartShoppingJPanel smartShoppingJPanel = (SmartShoppingJPanel) component;
        smartShoppingJPanel.startAdv();
        CardLayout layout = (CardLayout) this.userProcessContainer.getLayout();
        layout.previous(this.userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        // TODO add your handling code here:
        if (result.containsKey("recommendations")) {
        Object recommendationsObj = result.get("recommendations");
        
        if (recommendationsObj instanceof Map) {
            Map<String, List<Map<String, Object>>> recommendationsMap = 
                (Map<String, List<Map<String, Object>>>) recommendationsObj;
            
            // Generate email content
            StringBuilder emailBody = new StringBuilder();
            emailBody.append("<p>Hi ").append(this.userAccount.getPerson().getPersonName()).append(", thank you for placing an order with MinFoo. Your order will be delivered soon!</p>");
            emailBody.append("<table style='border-collapse: collapse; width: 100%;'>");
            emailBody.append("<thead>");
            emailBody.append("<tr>");
            emailBody.append("<th style='border: 1px solid #000; padding: 8px; text-align: left; font-weight: bold;'>Product</th>");
            emailBody.append("<th style='border: 1px solid #000; padding: 8px; text-align: left; font-weight: bold;'>Store Name</th>");
            emailBody.append("<th style='border: 1px solid #000; padding: 8px; text-align: left; font-weight: bold;'>Price</th>");
            emailBody.append("<th style='border: 1px solid #000; padding: 8px; text-align: left; font-weight: bold;'>Quantity</th>");
            emailBody.append("<th style='border: 1px solid #000; padding: 8px; text-align: left; font-weight: bold;'>Item Total</th>");
            emailBody.append("<th style='border: 1px solid #000; padding: 8px; text-align: left; font-weight: bold;'>Store Distance</th>");
            emailBody.append("</tr>");
            emailBody.append("</thead>");
            emailBody.append("<tbody>");
            
            Order newOrder = this.userAccount.getCustOrders().newOrder();
            
            for (Map.Entry<String, List<Map<String, Object>>> entry : recommendationsMap.entrySet()) {
                List<Map<String, Object>> storeDetails = entry.getValue();
                
                for (Map<String, Object> storeDetail : storeDetails) {
                    String price = String.valueOf(storeDetail.get("price"));
                    String qAvl = String.valueOf(storeDetail.get("quantityAvailable"));
                    
                    if (price != storeDetail.get("price") || qAvl.equalsIgnoreCase("N/A")) {
                        Product orderProd = (Product) storeDetail.get("productName");
                        SuperMarketEnterprise store = (SuperMarketEnterprise) storeDetail.get("storeName");
                        String qFulfil = String.valueOf(storeDetail.get("quantityFulfilled"));
                        String dist = String.valueOf(storeDetail.get("distance"));
                        
                        OrderItem newOrderItem = newOrder.addOrderItem(orderProd, Integer.parseInt(qFulfil), store);
                        
                        emailBody.append("<tr>");
                        emailBody.append("<td style='border: 1px solid #000; padding: 8px;'>").append(orderProd.getProdName()).append("</td>");
                        emailBody.append("<td style='border: 1px solid #000; padding: 8px;'>").append(store.getOrgName()).append("</td>");
                        emailBody.append("<td style='border: 1px solid #000; padding: 8px;'>").append(price).append("</td>");
                        emailBody.append("<td style='border: 1px solid #000; padding: 8px;'>").append(qFulfil).append("</td>");
                        emailBody.append("<td style='border: 1px solid #000; padding: 8px;'>").append(newOrderItem.getOrderItemTotal()).append("</td>");
                        emailBody.append("<td style='border: 1px solid #000; padding: 8px;'>").append(dist).append("</td>");
                        emailBody.append("</tr>");
                    }
                }
            }
            
            this.userAccount.getCustOrders().addSmartOrder(newOrder);
            emailBody.append("</tbody></table>");
            emailBody.append("<p>Order Total: ").append(newOrder.getTransactionAmount()).append("</p>");
            
            // Generate email subject
            String emailSubject = "Order#" + newOrder.getOrderID() + " has been placed with MinFoo";
            
            // Send the email
            sendEmail("aishwaryaadusumelli07@gmail.com", emailSubject, emailBody.toString());
//            sendEmail(this.userAccount.getUsername(), emailSubject, emailBody.toString());
        }
    }
    
    JOptionPane.showMessageDialog(this, "Thank you for ordering. Order has been placed successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
    
    // Stop the advertisements
    stopAdv();
    
    this.userProcessContainer.remove(this);
    Component[] componentArray = this.userProcessContainer.getComponents();
    Component component = componentArray[componentArray.length - 1];
    SmartShoppingJPanel customerCartJPanel = (SmartShoppingJPanel) component;
    customerCartJPanel.resetCart();
    customerCartJPanel.startAdv();
    CardLayout layout = (CardLayout) this.userProcessContainer.getLayout();
    layout.previous(this.userProcessContainer);
    }//GEN-LAST:event_btnPayActionPerformed

    private void populateOrderTable() {
        DefaultTableModel model = (DefaultTableModel) tblViewOrder.getModel();
        model.setRowCount(0);
        
        // Iterating the result map
        if (result.containsKey("recommendations")) {
            Object recommendationsObj = result.get("recommendations");
            
            if (recommendationsObj instanceof Map) {
                Map<String, List<Map<String, Object>>> recommendationsMap = 
                    (Map<String, List<Map<String, Object>>>) recommendationsObj;

                for (Map.Entry<String, List<Map<String, Object>>> entry : recommendationsMap.entrySet()) {
                    String productName = entry.getKey();
                    List<Map<String, Object>> storeDetails = entry.getValue();

                    //System.out.println("Product: " + productName);

                    for (Map<String, Object> storeDetail : storeDetails) {
                        String storeName = "";
                        try {
                            SuperMarketEnterprise store = (SuperMarketEnterprise) storeDetail.get("storeName");
                            storeName = (String) store.getOrgName();
                        } catch (Exception e) {
                            storeName = (String) storeDetail.get("storeName");
                        }
                        //System.out.println("  Store Name: " + storeName);
                        
                        
                        String price = String.valueOf(storeDetail.get("price"));
                        //System.out.println("  Price: " + price);
                        
                        String qAvl = String.valueOf(storeDetail.get("quantityAvailable"));
                        //System.out.println("  Quantity Available: " + qAvl);
                        
                        String qFulfil = String.valueOf(storeDetail.get("quantityFulfilled"));
                        //System.out.println("  Quantity Fulfilled: " + qFulfil);
                        
                        String dist = String.valueOf(storeDetail.get("distance"));
                        //System.out.println("  Distance: " + dist);
                        
                        float totCost;
                        
                        try {
                            totCost = (Integer) storeDetail.get("quantityFulfilled") * (float) storeDetail.get("price");
                        } catch (Exception e) {
                            totCost = 0;
                        }
                        
                        
                        Object row[] = new Object[6];
                        row[0] = productName;
                        row[1] = qFulfil;
                        row[2] = price;
                        row[3] = storeName;
                        row[4] = totCost;
                        row[5] = dist;
                        model.addRow(row);
                    }
                }
            }
        }
    }
    
    public void startAdv() {
        // Initialize and start the AdvertisementDisplay thread
        adDisplay = new AdvertisementDisplay(this.custAdvList, imageAdvertisement, this.userAccount.getUsername());
    }
    
    public void stopAdv() {
        // Stop the running advertisements
        this.adDisplay.stopAdvertisementDisplay();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnPay;
    private javax.swing.JLabel imageAdvertisement;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblOrderTot;
    private javax.swing.JLabel lblTotOrdAmt;
    private javax.swing.JTable tblViewOrder;
    // End of variables declaration//GEN-END:variables
}
