/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.CustomerRole;

import Business.AdvManagement.AdvertisementCatalog;
import Business.AdvManagement.AdvertisementDisplay;
import Business.Enterprise.Enterprise;
import Business.OrderManagement.Order;
import Business.OrderManagement.OrderItem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aakashbelide
 */
public class ViewOrderJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    Order selectedOrder;
    UserAccount userAccount;
    AdvertisementCatalog custAdvList;
    AdvertisementDisplay adDisplay;
    Enterprise enterprise;

    /**
     * Creates new form ViewOrderJPanel
     */
    public ViewOrderJPanel(JPanel userProcessContainer, Order selectedOrder, UserAccount userAccount, AdvertisementCatalog custAdvList ,Enterprise enterprise) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.selectedOrder = selectedOrder;
        this.userAccount = userAccount;
        this.custAdvList = custAdvList;
        this.enterprise = enterprise;
        
        // Start the advertisements
        startAdv();
        
        populateOrderItemsTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrderItems = new javax.swing.JTable();
        lblTotOrderAmt = new javax.swing.JLabel();
        lblOrderAmt = new javax.swing.JLabel();
        btnFeedback = new javax.swing.JButton();
        btnRaiseReq = new javax.swing.JButton();
        imageAdvertisement = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        btnBack.setBackground(new java.awt.Color(0, 153, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/arrow.png"))); // NOI18N
        btnBack.setBorder(null);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        Title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("View Order");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(btnBack)
                .addGap(44, 44, 44)
                .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                .addGap(163, 163, 163))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Title)
                    .addComponent(btnBack))
                .addGap(38, 38, 38))
        );

        tblOrderItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Product", "Quantity", "Price", "Market Name", "Total Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblOrderItems);

        lblTotOrderAmt.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        lblTotOrderAmt.setText("Order Total:");

        lblOrderAmt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrderAmt.setText("$ 0");

        btnFeedback.setBackground(new java.awt.Color(0, 153, 255));
        btnFeedback.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnFeedback.setForeground(new java.awt.Color(255, 255, 255));
        btnFeedback.setText("Give Feedback");
        btnFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFeedbackActionPerformed(evt);
            }
        });

        btnRaiseReq.setBackground(new java.awt.Color(0, 153, 255));
        btnRaiseReq.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnRaiseReq.setForeground(new java.awt.Color(255, 255, 255));
        btnRaiseReq.setText("Raise Request");
        btnRaiseReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaiseReqActionPerformed(evt);
            }
        });

        imageAdvertisement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageAdvertisement.setText("<Advertisement>");
        imageAdvertisement.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTotOrderAmt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblOrderAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFeedback)
                        .addGap(18, 18, 18)
                        .addComponent(btnRaiseReq))
                    .addComponent(jScrollPane1))
                .addGap(35, 35, 35)
                .addComponent(imageAdvertisement, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageAdvertisement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblTotOrderAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblOrderAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnRaiseReq, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(83, 83, 83)))
                .addGap(107, 107, 107))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        // Stop the advertisements
        stopAdv();
        
        this.userProcessContainer.remove(this);
        Component[] componentArray = this.userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CustomerOrdersJPanel customerOrdersJPanel = (CustomerOrdersJPanel) component;
        customerOrdersJPanel.startAdv();
        CardLayout layout = (CardLayout) this.userProcessContainer.getLayout();
        layout.previous(this.userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRaiseReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaiseReqActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblOrderItems.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select an order item first.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        OrderItem selectedOrderItem = (OrderItem) tblOrderItems.getValueAt(selectedRowIndex, 0);
        
        // TO-DO: Show new page with option for the user to raise a request for the selected orderitem

        RaiseReqJPanel raiseReqJPanel = new RaiseReqJPanel(this.userProcessContainer, selectedOrderItem, this.userAccount, this.custAdvList,this.enterprise);
        this.userProcessContainer.add("RaiseReqJPanel", raiseReqJPanel);
        CardLayout layout=(CardLayout)this.userProcessContainer.getLayout();
        layout.next(this.userProcessContainer);
    }//GEN-LAST:event_btnRaiseReqActionPerformed

    private void btnFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFeedbackActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblOrderItems.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select an order item first.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        OrderItem selectedOrderItem = (OrderItem) tblOrderItems.getValueAt(selectedRowIndex, 0);
        
        // TO-DO: Show new page with option for the user to give feedback for the selected orderitem
        
        ItemFeedbaackJPanel itemFeedbaackJPanel = new ItemFeedbaackJPanel(this.userProcessContainer, selectedOrderItem, this.userAccount, this.custAdvList);
        this.userProcessContainer.add("ItemFeedbaackJPanel", itemFeedbaackJPanel);
        CardLayout layout=(CardLayout)this.userProcessContainer.getLayout();
        layout.next(this.userProcessContainer);
    }//GEN-LAST:event_btnFeedbackActionPerformed

    public void populateOrderItemsTable() {
        DefaultTableModel model = (DefaultTableModel) tblOrderItems.getModel();
        model.setRowCount(0);
        
        float totalOrderAmount = 0;

        for (OrderItem orderItem : this.selectedOrder.getOrderItems()) {
            Object row[] = new Object[5];
            row[0] = orderItem;
            row[1] = orderItem.getItemQuant();
            row[2] = orderItem.getBuyPrice();
            row[3] = orderItem.getMarket();
            float orderItemAmount = orderItem.getOrderItemTotal();
            row[4] = orderItemAmount;
            totalOrderAmount = totalOrderAmount + orderItemAmount;
            model.addRow(row);
        }
        
        lblOrderAmt.setText("$ " + String.valueOf(totalOrderAmount));
    }
    
    public void startAdv() {
        // Initialize and start the AdvertisementDisplay thread
        adDisplay = new AdvertisementDisplay(this.custAdvList, imageAdvertisement, this.userAccount.getUsername());
    }
    
    public void stopAdv() {
        // Stop the running advertisements
        this.adDisplay.stopAdvertisementDisplay();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnFeedback;
    private javax.swing.JButton btnRaiseReq;
    private javax.swing.JLabel imageAdvertisement;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblOrderAmt;
    private javax.swing.JLabel lblTotOrderAmt;
    private javax.swing.JTable tblOrderItems;
    // End of variables declaration//GEN-END:variables
}
